// Role-based access control definitions

export type UserRole = 'super_admin' | 'clinic_admin' | 'staff' | 'clinician' | 'sales' | 'trainer'

export interface Permission {
  resource: string
  action: string
}

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  super_admin: [
    { resource: 'users', action: 'create' },
    { resource: 'users', action: 'read' },
    { resource: 'users', action: 'update' },
    { resource: 'users', action: 'delete' },
    { resource: 'memberships', action: 'create' },
    { resource: 'memberships', action: 'read' },
    { resource: 'memberships', action: 'update' },
    { resource: 'memberships', action: 'delete' },
    { resource: 'therapies', action: 'create' },
    { resource: 'therapies', action: 'read' },
    { resource: 'therapies', action: 'update' },
    { resource: 'therapies', action: 'delete' },
    { resource: 'bookings', action: 'create' },
    { resource: 'bookings', action: 'read' },
    { resource: 'bookings', action: 'update' },
    { resource: 'bookings', action: 'delete' },
    { resource: 'dna', action: 'create' },
    { resource: 'dna', action: 'read' },
    { resource: 'dna', action: 'update' },
    { resource: 'dna', action: 'delete' },
    { resource: 'reports', action: 'create' },
    { resource: 'reports', action: 'read' },
    { resource: 'reports', action: 'update' },
    { resource: 'reports', action: 'delete' },
    { resource: 'leads', action: 'create' },
    { resource: 'leads', action: 'read' },
    { resource: 'leads', action: 'update' },
    { resource: 'leads', action: 'delete' },
    { resource: 'nutrition', action: 'create' },
    { resource: 'nutrition', action: 'read' },
    { resource: 'nutrition', action: 'update' },
    { resource: 'nutrition', action: 'delete' },
    { resource: 'sports_scientist', action: 'create' },
    { resource: 'sports_scientist', action: 'read' },
    { resource: 'sports_scientist', action: 'update' },
    { resource: 'sports_scientist', action: 'delete' },
    { resource: 'audit_logs', action: 'read' },
    { resource: 'attendance', action: 'read' },
    { resource: 'attendance', action: 'create' },
    { resource: 'attendance', action: 'update' },
    { resource: 'settings', action: 'read' },
    { resource: 'settings', action: 'update' },
  ],
  clinic_admin: [
    { resource: 'users', action: 'read' },
    { resource: 'users', action: 'update' },
    { resource: 'users', action: 'create' },
    { resource: 'memberships', action: 'create' },
    { resource: 'memberships', action: 'read' },
    { resource: 'memberships', action: 'update' },
    { resource: 'therapies', action: 'create' },
    { resource: 'therapies', action: 'read' },
    { resource: 'therapies', action: 'update' },
    { resource: 'bookings', action: 'create' },
    { resource: 'bookings', action: 'read' },
    { resource: 'bookings', action: 'update' },
    { resource: 'dna', action: 'read' },
    { resource: 'dna', action: 'update' },
    { resource: 'reports', action: 'read' },
    { resource: 'leads', action: 'read' },
    { resource: 'leads', action: 'update' },
    { resource: 'nutrition', action: 'create' },
    { resource: 'nutrition', action: 'read' },
    { resource: 'nutrition', action: 'update' },
    { resource: 'nutrition', action: 'delete' },
    { resource: 'sports_scientist', action: 'create' },
    { resource: 'sports_scientist', action: 'read' },
    { resource: 'sports_scientist', action: 'update' },
    { resource: 'sports_scientist', action: 'delete' },
    { resource: 'audit_logs', action: 'read' },
    { resource: 'attendance', action: 'read' },
    { resource: 'attendance', action: 'create' },
    { resource: 'attendance', action: 'update' },
    { resource: 'settings', action: 'read' },
  ],
  staff: [
    { resource: 'users', action: 'read' },
    { resource: 'memberships', action: 'read' },
    { resource: 'therapies', action: 'read' },
    { resource: 'bookings', action: 'read' },
    { resource: 'bookings', action: 'update' },
    { resource: 'dna', action: 'read' },
    { resource: 'reports', action: 'read' },
    { resource: 'nutrition', action: 'read' },
    { resource: 'sports_scientist', action: 'read' },
    { resource: 'sports_scientist', action: 'update' },
    { resource: 'attendance', action: 'read' },
    { resource: 'attendance', action: 'create' },
    { resource: 'attendance', action: 'update' },
  ],
  clinician: [
    { resource: 'users', action: 'read' },
    { resource: 'bookings', action: 'read' },
    { resource: 'bookings', action: 'update' },
    { resource: 'schedules', action: 'read' },
    { resource: 'schedules', action: 'update' },
    { resource: 'dna', action: 'read' },
    { resource: 'dna', action: 'update' },
    { resource: 'reports', action: 'read' },
    { resource: 'reports', action: 'create' },
    { resource: 'nutrition', action: 'read' },
    { resource: 'nutrition', action: 'update' },
    { resource: 'sports_scientist', action: 'read' },
    { resource: 'sports_scientist', action: 'update' },
  ],
  sales: [
    { resource: 'leads', action: 'read' },
    { resource: 'leads', action: 'create' },
    { resource: 'leads', action: 'update' },
    { resource: 'memberships', action: 'read' },
  ],
  trainer: [
    { resource: 'users', action: 'read' },
    { resource: 'workout_plans', action: 'create' },
    { resource: 'workout_plans', action: 'read' },
    { resource: 'workout_plans', action: 'update' },
    { resource: 'workout_sessions', action: 'create' },
    { resource: 'workout_sessions', action: 'read' },
    { resource: 'workout_sessions', action: 'update' },
    { resource: 'exercises', action: 'read' },
  ],
}

export function hasPermission(role: UserRole, resource: string, action: string): boolean {
  const permissions = ROLE_PERMISSIONS[role]
  return permissions.some(p => p.resource === resource && p.action === action)
}
